### PR TITLE
Add WorldControlState msg type

### PR DESCRIPTION
**Pull request by adlarkin**
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>

# 🎉 New feature

Part of https://github.com/ignitionrobotics/ign-gazebo/issues/1106

## Summary
As discussed in https://github.com/ignitionrobotics/design/pull/8#discussion_r728391135, if the GUI's ECM is updated while simulation is paused, the GUI should share any ECM updates that occurred with the server when simulation is resumed. This PR creates a `WorldControlState` message to accomplish this. This message type contains both `WorldControl` and a `SerializedState` (the `SerializedState` can be used to contain ECM information, and `WorldControl` is used for the same purpose - play/pause/step).

## Test it
This message can be tested with https://github.com/ignitionrobotics/ign-gazebo/pull/1109.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Review by chapulina — DISMISSED** [review]
This looks ok to me as is, but I'd like the full implementation to be complete and iterated on before merging. This is targeting a release branch, so once it's merged / released, we can't change it.

Leaving a "request changes" to signify this.

**Comment by nkoenig** [comment]
Targeting `fortress` is fine for the subt work.

**Comment by adlarkin** [comment]
All review feedback has been addressed. As mentioned previously, if this goes into Fortress, the message types can't be changed once they're merged. So, I will hold off on merging this until https://github.com/ignitionrobotics/ign-gui/pull/306 and https://github.com/ignitionrobotics/ign-gazebo/pull/1109 are finalized.

**Comment by adlarkin** [comment]
Following the discussion I had with @nkoenig in https://github.com/ignitionrobotics/ign-gazebo/pull/1109#issuecomment-953472995, I've updated this PR to only create a `WorldControlState` msg type. We do not need the `SerializedState_V` msg type for achieving https://github.com/ignitionrobotics/ign-gazebo/issues/1106.

**Comment by nkoenig** [comment]
I've tested this with https://github.com/ignitionrobotics/ign-gui/pull/306 and it seems to work well. I'll merge and get a release out the door so that we can move forward with downstream PRs.

**Pull request merged**
