### PR TITLE
fixed a comment in the Image.proto file

### PR DESCRIPTION
**Pull request by addy1997**
changed the spelling of `wisth` to `width`. Please follow (#160).

### CODE REVIEW

**Comment by addy1997** [comment]
@ahcorde, I have made a new PR. Please refer to this [commit](https://github.com/ignitionrobotics/ign-msgs/pull/161/commits/872c84270da513a43775a7c691780aad33d07bed) for details.

Thanks

**Review by ahcorde — CHANGES_REQUESTED** [review]
There PR has two commits, can you remove this one https://github.com/ignitionrobotics/ign-msgs/pull/161/commits/c2277681000ae0cf726241d9026531ee8860f633 ?

**Comment by addy1997** [comment]
> This is happening probably because you have an outdated branch.
> 
> ```
> # Keep you changes in a new branch
> git checkout -b comment-fixed_old
> # checkout ign-msgs7
> git checkout ign-msgs7
> # update the branch
> git pull origin ign-msgs7
> # Remove the old branch
> git branch -D comment-fixed
> # created a new branch based on the recent changes
> git checkout -b comment-fixed
> # Include your changes
> git cherry-pick e2c81c46b6db5c6ff4413f975e2a1d57d0c5a114
> # push changes to your branch
> git push -f origin comment-fixed
> ```

I have done it. Thanks a lot.

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
Thank you for iterating @addy1997

**Pull request merged**
